fixed a couple of code smells
SE2-Gruppe-E-Royal-Dog/GruppenPhaseAndroid pull request #88
Opened 2022-05-29 18:31 UTC by SandroLinder

2022-05-29 21:21 UTC, TheNerm approved these changes

2022-05-30 05:54 UTC, d2rainer requested changes
Bitte Figure und alle Subklassen herausnehmen, da ich sie umgebaut habe => sonst conflict

2022-05-30 05:54 UTC, d2rainer commented
Bitte nicht mergen - habe Figure und alle Subklassen neu umgebaut, da sie tlw. nicht funktioniert haben. Ansonsten haben wir Konflikte....

2022-05-30 18:35 UTC, d2rainer approved these changes

2022-06-09 10:44 UTC, closed without merging